language: java
jdk:
  - openjdk8
  - openjdk11
  
after_success:
  - mvn clean cobertura:cobertura coveralls:report

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/