/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 5.0 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTSINGLESTATEMENT = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTERROR_SKIPTO = 3;
  public int JJTSET = 4;
  public int JJTUPDATE = 5;
  public int JJTREPLACE = 6;
  public int JJTLISTEXPRESSIONITEM = 7;
  public int JJTINSERT = 8;
  public int JJTUPSERT = 9;
  public int JJTDELETE = 10;
  public int JJTMERGE = 11;
  public int JJTMERGEUPDATECLAUSE = 12;
  public int JJTMERGEINSERTCLAUSE = 13;
  public int JJTCOLUMN = 14;
  public int JJTRELOBJECTNAME = 15;
  public int JJTRELOBJECTNAMEEXT = 16;
  public int JJTRELOBJECTNAMEEXT2 = 17;
  public int JJTTABLE = 18;
  public int JJTTABLEWITHALIAS = 19;
  public int JJTSELECT = 20;
  public int JJTSELECTBODY = 21;
  public int JJTPLAINSELECT = 22;
  public int JJTSETOPERATIONLIST = 23;
  public int JJTWITHLIST = 24;
  public int JJTWITHITEM = 25;
  public int JJTSELECTITEMSLIST = 26;
  public int JJTSELECTEXPRESSIONITEM = 27;
  public int JJTSELECTITEM = 28;
  public int JJTALLTABLECOLUMNS = 29;
  public int JJTALIAS = 30;
  public int JJTFUNCTIONITEM = 31;
  public int JJTPIVOTFORCOLUMNS = 32;
  public int JJTPIVOTFUNCTIONITEMS = 33;
  public int JJTPIVOTSINGLEINITEMS = 34;
  public int JJTEXPRESSIONLISTITEM = 35;
  public int JJTPIVOTMULTIINITEMS = 36;
  public int JJTPIVOT = 37;
  public int JJTPIVOTXML = 38;
  public int JJTINTOCLAUSE = 39;
  public int JJTFROMITEM = 40;
  public int JJTVALUESLIST = 41;
  public int JJTLATERALSUBSELECT = 42;
  public int JJTSUBJOIN = 43;
  public int JJTJOINSLIST = 44;
  public int JJTJOINEREXPRESSION = 45;
  public int JJTWHERECLAUSE = 46;
  public int JJTORACLEHIERARCHICALQUERYCLAUSE = 47;
  public int JJTGROUPBYCOLUMNREFERENCES = 48;
  public int JJTHAVING = 49;
  public int JJTORDERBYELEMENTS = 50;
  public int JJTORDERBYELEMENT = 51;
  public int JJTLIMITWITHOFFSET = 52;
  public int JJTPLAINLIMIT = 53;
  public int JJTOFFSET = 54;
  public int JJTFETCH = 55;
  public int JJTTOP = 56;
  public int JJTSKIP = 57;
  public int JJTGETORACLEHINT = 58;
  public int JJTFIRST = 59;
  public int JJTEXPRESSION = 60;
  public int JJTOREXPRESSION = 61;
  public int JJTANDEXPRESSION = 62;
  public int JJTCONDITION = 63;
  public int JJTREGULARCONDITION = 64;
  public int JJTSQLCONDITION = 65;
  public int JJTINEXPRESSION = 66;
  public int JJTBETWEEN = 67;
  public int JJTLIKEEXPRESSION = 68;
  public int JJTISNULLEXPRESSION = 69;
  public int JJTEXISTSEXPRESSION = 70;
  public int JJTSQLEXPRESSIONLIST = 71;
  public int JJTSIMPLEEXPRESSIONLIST = 72;
  public int JJTSIMPLEEXPRESSIONLISTATLEASTTWOITEMS = 73;
  public int JJTCOMPARISONITEM = 74;
  public int JJTALLCOMPARISONEXPRESSION = 75;
  public int JJTANYCOMPARISONEXPRESSION = 76;
  public int JJTSIMPLEEXPRESSION = 77;
  public int JJTCONCATEXPRESSION = 78;
  public int JJTBITWISEANDOR = 79;
  public int JJTADDITIVEEXPRESSION = 80;
  public int JJTMULTIPLICATIVEEXPRESSION = 81;
  public int JJTBITWISEXOR = 82;
  public int JJTPRIMARYEXPRESSION = 83;
  public int JJTJDBCNAMEDPARAMETER = 84;
  public int JJTUSERVARIABLE = 85;
  public int JJTNUMERICBIND = 86;
  public int JJTDATETIMELITERALEXPRESSION = 87;
  public int JJTJSONEXPRESSION = 88;
  public int JJTINTERVALEXPRESSION = 89;
  public int JJTWITHINGROUPEXPRESSION = 90;
  public int JJTKEEPEXPRESSION = 91;
  public int JJTANALYTICEXPRESSION = 92;
  public int JJTWINDOWELEMENT = 93;
  public int JJTWINDOWOFFSET = 94;
  public int JJTEXTRACTEXPRESSION = 95;
  public int JJTCASTEXPRESSION = 96;
  public int JJTCASEWHENEXPRESSION = 97;
  public int JJTWHENTHENSEARCHCONDITION = 98;
  public int JJTWHENTHENVALUE = 99;
  public int JJTROWCONSTRUCTOR = 100;
  public int JJTEXECUTE = 101;
  public int JJTFUNCTION = 102;
  public int JJTMYSQLGROUPCONCAT = 103;
  public int JJTTABLEFUNCTION = 104;
  public int JJTSUBSELECT = 105;
  public int JJTCREATEINDEX = 106;
  public int JJTCREATETABLE = 107;
  public int JJTCOLDATATYPE = 108;
  public int JJTCREATEVIEW = 109;
  public int JJTALTERVIEW = 110;
  public int JJTCREATEPARAMETER = 111;
  public int JJTALIST = 112;
  public int JJTCOLUMNSNAMESLIST = 113;
  public int JJTDROP = 114;
  public int JJTTRUNCATE = 115;
  public int JJTALTEREXPRESSION = 116;
  public int JJTALTERTABLE = 117;


  public String[] jjtNodeName = {
    "Statement",
    "SingleStatement",
    "Statements",
    "error_skipto",
    "Set",
    "Update",
    "Replace",
    "ListExpressionItem",
    "Insert",
    "Upsert",
    "Delete",
    "Merge",
    "MergeUpdateClause",
    "MergeInsertClause",
    "Column",
    "RelObjectName",
    "RelObjectNameExt",
    "RelObjectNameExt2",
    "Table",
    "TableWithAlias",
    "Select",
    "SelectBody",
    "PlainSelect",
    "SetOperationList",
    "WithList",
    "WithItem",
    "SelectItemsList",
    "SelectExpressionItem",
    "SelectItem",
    "AllTableColumns",
    "Alias",
    "FunctionItem",
    "PivotForColumns",
    "PivotFunctionItems",
    "PivotSingleInItems",
    "ExpressionListItem",
    "PivotMultiInItems",
    "Pivot",
    "PivotXml",
    "IntoClause",
    "FromItem",
    "ValuesList",
    "LateralSubSelect",
    "SubJoin",
    "JoinsList",
    "JoinerExpression",
    "WhereClause",
    "OracleHierarchicalQueryClause",
    "GroupByColumnReferences",
    "Having",
    "OrderByElements",
    "OrderByElement",
    "LimitWithOffset",
    "PlainLimit",
    "Offset",
    "Fetch",
    "Top",
    "Skip",
    "getOracleHint",
    "First",
    "Expression",
    "OrExpression",
    "AndExpression",
    "Condition",
    "RegularCondition",
    "SQLCondition",
    "InExpression",
    "Between",
    "LikeExpression",
    "IsNullExpression",
    "ExistsExpression",
    "SQLExpressionList",
    "SimpleExpressionList",
    "SimpleExpressionListAtLeastTwoItems",
    "ComparisonItem",
    "AllComparisonExpression",
    "AnyComparisonExpression",
    "SimpleExpression",
    "ConcatExpression",
    "BitwiseAndOr",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "BitwiseXor",
    "PrimaryExpression",
    "JdbcNamedParameter",
    "UserVariable",
    "NumericBind",
    "DateTimeLiteralExpression",
    "JsonExpression",
    "IntervalExpression",
    "WithinGroupExpression",
    "KeepExpression",
    "AnalyticExpression",
    "WindowElement",
    "WindowOffset",
    "ExtractExpression",
    "CastExpression",
    "CaseWhenExpression",
    "WhenThenSearchCondition",
    "WhenThenValue",
    "RowConstructor",
    "Execute",
    "Function",
    "MySQLGroupConcat",
    "TableFunction",
    "SubSelect",
    "CreateIndex",
    "CreateTable",
    "ColDataType",
    "CreateView",
    "AlterView",
    "CreateParameter",
    "AList",
    "ColumnsNamesList",
    "Drop",
    "Truncate",
    "AlterExpression",
    "AlterTable",
  };
}
/* JavaCC - OriginalChecksum=847dc47f5a3559871c95abce2fc00eeb (do not edit this line) */
