/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 6.1_2 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=87e5f128287d555857ce2257554edd12 (do not edit this line) */
