/* Generated By:JavaCC: Do not edit this line. CCJSqlParserDefaultVisitor.java Version 6.1_2 */
package net.sf.jsqlparser.parser;

public class CCJSqlParserDefaultVisitor implements CCJSqlParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=229e159de0e4470cc9381816c06b28b4 (do not edit this line) */
