/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2019 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
package net.sf.jsqlparser.statement.select;

import java.io.Serializable;

import net.sf.jsqlparser.expression.Expression;
import net.sf.jsqlparser.schema.Column;

/**
 * Models one column entry of the ClickHouse {@code INTERPOLATE} clause, which computes the values
 * of non-sorted columns for the rows generated by {@code ORDER BY ... WITH FILL} (see
 * <a href="https://clickhouse.com/docs/en/sql-reference/statements/select/order-by">ClickHouse:
 * ORDER BY</a>).
 * <p>
 * {@code col AS expr} evaluates {@code expr} for the generated rows, while a bare {@code col} (a
 * {@code null} expression) repeats the previous value of the column.
 */
public class InterpolateElement implements Serializable {

    private Column column;
    private Expression expression;

    public InterpolateElement() {
        super();
    }

    public InterpolateElement(Column column, Expression expression) {
        this.column = column;
        this.expression = expression;
    }

    public Column getColumn() {
        return column;
    }

    public void setColumn(Column column) {
        this.column = column;
    }

    public InterpolateElement withColumn(Column column) {
        setColumn(column);
        return this;
    }

    public Expression getExpression() {
        return expression;
    }

    public void setExpression(Expression expression) {
        this.expression = expression;
    }

    public InterpolateElement withExpression(Expression expression) {
        setExpression(expression);
        return this;
    }

    @Override
    public String toString() {
        if (expression != null) {
            return column + " AS " + expression;
        }
        return column.toString();
    }
}
