/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2026 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
package net.sf.jsqlparser.statement.create;

import static org.junit.jupiter.api.Assertions.*;
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.AbstractJSqlParser.Dialect;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.schema.Sequence;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.alter.Alter;
import net.sf.jsqlparser.statement.create.table.CreateTable;
import net.sf.jsqlparser.statement.create.table.IdentityDefinition;
import net.sf.jsqlparser.util.deparser.StatementDeParser;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class IdentitySequenceNameTest {
    @ParameterizedTest
    @ValueSource(strings = {"ids", "public.ids", "\"schema.name\".\"seq.name\""})
    void sharesIdentityOptionsAcrossCreateAndAlter(String name) throws JSQLParserException {
        String definition = "GENERATED BY DEFAULT AS IDENTITY (START 4 SEQUENCE NAME " + name
                + " CACHE 2 NO CYCLE)";
        CreateTable create = (CreateTable) parse("CREATE TABLE t (id INT " + definition + ")");
        IdentityDefinition identity = create.getColumnDefinitions().get(0).getColumnOptions().get(0)
                .getIdentityDefinition();
        Alter alter = (Alter) parse("ALTER TABLE t ALTER COLUMN id ADD " + definition);
        IdentityDefinition altered = alter.getAlterExpressions().get(0).getColDataTypeList().get(0)
                .getIdentityAlterations().get(0).getIdentityDefinition();
        for (IdentityDefinition current : new IdentityDefinition[] {identity, altered}) {
            assertEquals(4, current.getParameters().size());
            Sequence.Parameter named = current.getParameters().get(1);
            assertEquals(Sequence.ParameterType.SEQUENCE_NAME, named.getOption());
            assertEquals(name, named.getSequenceName().getFullyQualifiedName());
            assertNull(named.getValue());
            named.getSequenceName().setName("renamed");
        }
        assertTrue(create.toString().contains("renamed"));
        assertTrue(alter.toString().contains("renamed"));
        roundTrip(create);
        roundTrip(alter);
    }

    @Test
    void preservesNameOnlyAndDoesNotExtendStandaloneSequenceOptions() throws JSQLParserException {
        String sql = "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME ids))";
        assertEquals(sql, parse(sql).toString());
        roundTrip(parse(sql));
        for (String invalid : new String[] {
                "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME))",
                "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY ())",
                "CREATE SEQUENCE ids SEQUENCE NAME other_ids",
                "ALTER TABLE t ALTER COLUMN id SET SEQUENCE NAME other_ids"}) {
            assertThrows(JSQLParserException.class, () -> parse(invalid), invalid);
        }
    }

    private static Statement parse(String sql) throws JSQLParserException {
        return CCJSqlParserUtil.parse(sql, p -> p.withDialect(Dialect.POSTGRESQL));
    }

    private static void roundTrip(Statement statement) throws JSQLParserException {
        StringBuilder out = new StringBuilder();
        statement.accept(new StatementDeParser(out));
        assertEquals(statement.toString(), out.toString());
        assertEquals(out.toString(), parse(out.toString()).toString());
    }
}
